version: '3.8'

services:
  api:
    container_name: 'manager-api'
    build: ./
    volumes:
      - logs:/app/logs 
      - ./:/app
      - /app/node_modules
    env_file: 
      - ./.env
    environment:
      DB_URL: '${DB_URL}'
      ACCESS_TOKEN: '${ACCESS_TOKEN}'
      REFRESH_TOKEN: '${REFRESH_TOKEN}'
      USER_TOKEN: '${USER_TOKEN}'
      SMTP_HOST: '${SMTP_HOST}'
      SMTP_PORT: '${SMTP_PORT}'
      SMTP_USER: '${SMTP_USER}'
      SMTP_PASS: '${SMTP_PASS}'
      BASE_URL: '${BASE_URL}'
    ports: 
    - 3000:3000
volumes: 
  logs: