name: Open PR to Staging Branch on push
on:
  push:
    branches:
      - 'feat/*'
      - 'fix/*'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: Run tests
        run: npm run test
        env: 
          DB_URL: ${{ secrets.DB_URL }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          BASE_URL: ${{ secrets.BASE_URL }}
          QUOTE_URL: ${{ secrets.QUOTE_URL }}
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: 'staging'
          pr_title: 'Pulling ${{ github.ref }} into staging'
          pr_body: 'Pulling ${{ github.ref }} into staging -- ${{ github.actor }}'
          github_token: ${{ secrets.GITHUB_TOKEN }}